title: "Joel Juma"
email: your-email@example.com
description: >-
  Portfolio and Resume of Joel Juma — Developer, Teacher & Cybersecurity Enthusiast.

baseurl: "" # keep it empty for GitHub Pages root
url: "https://joeljumagithub.io"

# Build settings
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Include pages folder
include:
  - _pages

# Navigation Links
nav:
  - title: "Home"
    url: "/"
  - title: "Resume"
    url: /resume/
  - title: "Projects"
    url: /projects/

# Author info (optional)
author:
  name: "Joel Juma"
  avatar: "/assets/images/profile.png"
  bio: "Developer • ICT Trainer • Cloud & Security Enthusiast"
  location: "Kenya"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/JOELJUMA"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/joeljuma"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
